- name: Configure local workstation
  hosts: localhost
  gather_facts: true
  become: false
  vars:
    include_deprecated: "false"
  pre_tasks:
    - name: Populate variables
      include_vars:
        dir: ansible/vars
        ignore_unknown_extensions: True
        extensions:
          - ""
          - "yaml"
          - "yml"
          - "json"
      tags:
        - always

    - name: "Ensure directory exist"
      file:
        path: "{{ item }}"
        state: "directory"
        recurse: yes
      loop:
        - "{{ localbin_dir }}"
        - "{{ gitconfig_dir }}"
        - "{{ gitconfig_dir }}/cmd"
        - "{{ fonts_dir }}"
        - "{{ gnupg_dir }}"
        - "{{ ssh_dir }}"
      tags:
        - always

  tasks:
    - include: ansible/common.debian.yaml
      when: ansible_system == "Linux" and ansible_os_family == "Debian"
      tags:
        - common
        - packages

    - include: ansible/common.darwin.yaml
      when: ansible_system == "Darwin"
      tags:
        - common
        - packages

    - include: ansible/common.yaml
      tags:
        - common
        - packages

    - include: ansible/fonts.yaml
      tags:
        - fonts

    - include: ansible/languages.yaml
      tags:
        - proglang

    - include: ansible/kubectl.yaml
      tags:
        - kubectl

    - include: ansible/zsh.yaml
      tags:
        - zsh

    - include: ansible/toolkit.yaml
      tags:
        - toolkit

    - include: "{{ item }}"
      with_fileglob:
        - ansible/deprecated/*.yaml
      tags:
        - deprecated
      when: include_deprecated|bool

    - name: "Post installation"
      debug:
        msg: "{{ post_install.split('\n') }}"
      tags:
        - common
