post_install: |
  You need to change your current shell to use zsh.
  With running the following commands:
        chsh -s $(which zsh)

  You also need to run keybase with running the following commands:

        run_keybase

  Then after that you need to import your current pgp key from keybase,
  with running the following commands:

        keybase pgp export -s | gpg --import

  As the starter for populating the existing shell history please run the following commands:

        atuin import auto

# ------ Binary version ------
sops_version: "v3.6.1"

# ------ Directory ------
fonts_dir: "{% if ansible_system == 'Linux' %}{{ ansible_env.HOME }}/.local/share/fonts{% elif ansible_system == 'Darwin' %}{{ ansible_env.HOME }}/Library/Fonts{% endif %}"
localbin_dir: "{{ ansible_env.HOME }}/.local/bin"
gitconfig_dir: "{{ ansible_env.HOME }}/.local/git"
gnupg_dir: "{{ ansible_env.HOME }}/.gnupg"
ssh_dir: "{{ ansible_env.HOME }}/.ssh"

# ------ Fonts ------
powerline_fonts: no
nerd_fonts: yes

# ------ plugins ------
asdf_plugins:
  - name: direnv
    repo: ""
    versions: ["2.28.0"]
    global: "2.28.0"
  - name: kubectl
    repo: ""
    versions: ["1.20.13"]
    global: "1.20.13"
  - name: kubetail
    repo: "https://github.com/janpieper/asdf-kubetail.git"
    versions: ["1.6.13"]
    global: "1.6.13"
  - name: helm
    repo: ""
    versions: ["3.2.0"]
    global: "3.2.0"
  - name: helm-diff
    repo: ""
    versions: ["3.1.3"]
    global: "3.1.3"
  - name: helmfile
    repo: ""
    versions: ["0.142.0"]
    global: "0.142.0"
  - name: kustomize
    repo: ""
    versions: ["4.4.1"]
    global: "4.4.1"
  - name: gcloud
    repo: ""
    versions: ["367.0.0"]
    global: "367.0.0"
  - name: awscli
    repo: ""
    versions: ["2.2.22"]
    global: "2.2.22"
  - name: golang
    repo: ""
    versions: ["1.17.5", "1.18.6"]
    global: "1.18.6"
  - name: istioctl
    repo: https://github.com/virtualstaticvoid/asdf-istioctl
    versions: ["1.10.6"]
    global: "1.10.6"
  - name: terraform
    repo: https://github.com/asdf-community/asdf-hashicorp
    versions: ["0.15.5", "1.1.0", "1.2.0"]
    global: "0.15.5"
  - name: packer
    repo: https://github.com/asdf-community/asdf-hashicorp
    versions: ["1.7.8"]
    global: "1.7.8"
  - name: consul
    repo: https://github.com/asdf-community/asdf-hashicorp
    versions: ["1.12.0"]
    global: "1.12.0"
  - name: vault
    repo: https://github.com/asdf-community/asdf-hashicorp
    versions: ["1.10.3"]
    global: "1.10.3"
  - name: boundary
    repo: https://github.com/asdf-community/asdf-hashicorp
    versions: ["0.8.1"]
    global: "0.8.1"
  - name: teleport-ent
    repo: ""
    versions: ["9.3.6"]
    global: "9.3.6"
  - name: k3d
    repo: https://github.com/spencergilbert/asdf-k3d.git
    versions: ["latest"]
    global: "latest"

kubectl_plugins:
  - ctx
  - ns
  - ingress-nginx
  - cert-manager
  - istiolog

kubectl_plugins_unofficial:
  - name: kubectl-version_manager
    url: https://raw.githubusercontent.com/ardikabs/kubectl-version_manager/master/kubectl-version_manager
  - name: kubectl-ssh_jump
    url: https://raw.githubusercontent.com/ardikabs/kubectl-ssh_jump/master/kubectl-ssh_jump
  - name: kubectl-node_shell
    url: https://github.com/kvaps/kubectl-node-shell/raw/master/kubectl-node_shell
