post_install: |
  You need to change your current shell to use zsh.
  With running the following commands:
        chsh -s $(which zsh)

  You also need to run keybase with running the following commands:

        run_keybase

  Then after that you need to import your current pgp key from keybase,
  with running the following commands:

        keybase pgp export -s | gpg --import

  As the starter for populating the existing shell history please run the following commands:

        atuin import auto

# ------ Binary version ------
sops_version: "v3.6.1"

# ------ Directory ------
fonts_dir: "{% if ansible_system == 'Linux' %}{{ ansible_env.HOME }}/.local/share/fonts{% elif ansible_system == 'Darwin' %}{{ ansible_env.HOME }}/Library/Fonts{% endif %}"
localbin_dir: "{{ ansible_env.HOME }}/.local/bin"
gitconfig_dir: "{{ ansible_env.HOME }}/.local/git"
gnupg_dir: "{{ ansible_env.HOME }}/.gnupg"
ssh_dir: "{{ ansible_env.HOME }}/.ssh"

# ------ Fonts ------
powerline_fonts: no
nerd_fonts: yes

# ------ plugins ------
asdf_plugins:
  - name: direnv
    repo: ""
    versions: ["2.28.0"]
    global: "2.28.0"
  - name: kubectl
    repo: ""
    versions: ["1.23.17", "1.27.1"]
    global: "1.27.1"
  - name: kubetail
    repo: "https://github.com/janpieper/asdf-kubetail.git"
    versions: ["1.6.13"]
    global: "1.6.13"
  - name: helm
    repo: ""
    versions: ["3.8.2", "3.12.1"]
    global: "3.8.2"
  - name: helm-diff
    repo: ""
    versions: ["3.8.1"]
    global: "3.8.1"
  - name: helmfile
    repo: ""
    versions: ["0.155.0"]
    global: "0.155.0"
  - name: kustomize
    repo: ""
    versions: ["4.4.1"]
    global: "4.4.1"
  - name: gcloud
    repo: ""
    versions: ["403.0.0"]
    global: "403.0.0"
  - name: awscli
    repo: ""
    versions: ["2.2.22"]
    global: "2.2.22"
  - name: golang
    repo: ""
    versions: ["1.20.5"]
    global: "1.20.5"
  - name: istioctl
    repo: https://github.com/virtualstaticvoid/asdf-istioctl
    versions: ["1.18.2"]
    global: "1.18.2"
  - name: terraform
    repo: https://github.com/asdf-community/asdf-hashicorp
    versions: ["1.1.0", "1.2.0", "1.5.2"]
    global: "1.2.0"
  - name: packer
    repo: https://github.com/asdf-community/asdf-hashicorp
    versions: ["1.7.8"]
    global: "1.7.8"
  - name: consul
    repo: https://github.com/asdf-community/asdf-hashicorp
    versions: ["1.12.0"]
    global: "1.12.0"
  - name: vault
    repo: https://github.com/asdf-community/asdf-hashicorp
    versions: ["1.10.3"]
    global: "1.10.3"
  - name: boundary
    repo: https://github.com/asdf-community/asdf-hashicorp
    versions: ["0.8.1"]
    global: "0.8.1"
  - name: k3d
    repo: https://github.com/spencergilbert/asdf-k3d.git
    versions: ["latest"]
    global: "latest"
  - name: cilium-cli
    repo: https://github.com/carnei-ro/asdf-cilium-cli.git
    versions: ["0.14.7"]
    global: "0.14.7"
  - name: cilium-hubble
    repo: https://github.com/NitriKx/asdf-cilium-hubble.git
    versions: ["0.11.6"]
    global: "0.11.6"
  - name: operator-sdk
    repo: https://github.com/Medium/asdf-operator-sdk.git
    versions: ["1.30.0"]
    global: "1.30.0"

kubectl_plugins:
  - ctx
  - ns
  - cert-manager
  - istiolog
  - mtail
  - outdated
  - preflight
  - support-bundle

kubectl_plugins_unofficial:
  - name: kubectl-version_manager
    url: https://raw.githubusercontent.com/ardikabs/kubectl-version_manager/master/kubectl-version_manager
  - name: kubectl-ssh_jump
    url: https://raw.githubusercontent.com/ardikabs/kubectl-ssh_jump/master/kubectl-ssh_jump
  - name: kubectl-node_shell
    url: https://github.com/kvaps/kubectl-node-shell/raw/master/kubectl-node_shell
  - name: kubectl-ingress-nginx
    url: https://github.com/kubernetes/ingress-nginx/releases/download//kubectl-ingress-nginx_darwin_arm64.tar.gz
