post_install: |
  You need to change your current shell to use zsh.
  With running the following commands:
        chsh -s $(which zsh)

  You also need to run keybase with running the following commands:

        run_keybase

  Then after that you need to import your current pgp key from keybase,
  with running the following commands:

        keybase pgp export -s | gpg --import

  As the starter for populating the existing shell history please run the following commands:

        atuin import auto

# ------ Binary version ------
sops_version: "v3.6.1"

# ------ Directory ------
fonts_dir: "{% if ansible_system == 'Linux' %}{{ ansible_env.HOME }}/.local/share/fonts{% elif ansible_system == 'Darwin' %}{{ ansible_env.HOME }}/Library/Fonts{% endif %}"
localbin_dir: "{{ ansible_env.HOME }}/.local/bin"
gitconfig_dir: "{{ ansible_env.HOME }}/.local/git"
gnupg_dir: "{{ ansible_env.HOME }}/.gnupg"
ssh_dir: "{{ ansible_env.HOME }}/.ssh"

# ------ Fonts ------
powerline_fonts: no
nerd_fonts: yes

# ------ plugins ------
asdf_plugins:
  - name: gcloud
    repo: ""
    versions: ["403.0.0"]
    global: "403.0.0"
  - name: awscli
    repo: ""
    versions: ["2.2.22"]
    global: "2.2.22"
  - name: golang
    repo: ""
    versions: ["1.22.7", "1.23.1"]
    global: "1.23.1"
  - name: rust
    repo: "https://github.com/asdf-community/asdf-rust.git"
    versions: ["1.82.0"]
    global: "1.82.0"
  - name: kubectl
    repo: ""
    versions: ["1.26.15", "1.27.16", "1.30.6", "1.31.2"]
    global: "1.27.16"
  - name: helm
    repo: ""
    versions: ["3.12.3", "3.16.2"]
    global: "3.12.1"
  - name: helm-diff
    repo: ""
    versions: ["3.9.11"]
    global: "3.9.11"
  - name: helmfile
    repo: ""
    versions: ["0.169.1", "1.0.0-rc.7"]
    global: "0.169.1"
  - name: kustomize
    repo: ""
    versions: ["5.4.3"]
    global: "5.4.3"
  - name: sops
    repo: https://github.com/feniix/asdf-sops.git
    versions: ["3.7.3", "3.9.0"]
    global: "3.9.0"
  - name: istioctl
    repo: https://github.com/virtualstaticvoid/asdf-istioctl
    versions: ["1.18.2", "1.21.1", "1.22.6", "1.23.3"]
    global: "1.21.1"
  - name: terraform
    repo: https://github.com/asdf-community/asdf-hashicorp
    versions: ["1.5.2", "1.9.0"]
    global: "1.9.0"
  - name: terragrunt
    repo: https://github.com/lotia/asdf-terragrunt
    versions: ["0.67.16"]
    global: "0.67.16"
  - name: direnv
    repo: ""
    versions: ["latest"]
    global: "latest"
  - name: kubetail
    repo: "https://github.com/janpieper/asdf-kubetail.git"
    versions: ["latest"]
    global: "latest"
  - name: packer
    repo: https://github.com/asdf-community/asdf-hashicorp
    versions: ["latest"]
    global: "latest"
  - name: consul
    repo: https://github.com/asdf-community/asdf-hashicorp
    versions: ["latest"]
    global: "latest"
  - name: vault
    repo: https://github.com/asdf-community/asdf-hashicorp
    versions: ["latest"]
    global: "latest"
  - name: boundary
    repo: https://github.com/asdf-community/asdf-hashicorp
    versions: ["latest"]
    global: "latest"
  - name: k3d
    repo: https://github.com/spencergilbert/asdf-k3d.git
    versions: ["latest"]
    global: "latest"
  - name: cilium-cli
    repo: https://github.com/carnei-ro/asdf-cilium-cli.git
    versions: ["latest"]
    global: "latest"
  - name: cilium-hubble
    repo: https://github.com/NitriKx/asdf-cilium-hubble.git
    versions: ["latest"]
    global: "latest"
  - name: operator-sdk
    repo: https://github.com/Medium/asdf-operator-sdk.git
    versions: ["latest"]
    global: "latest"
  - name: mockery
    repo: https://github.com/cabify/asdf-mockery.git
    versions: ["latest"]
    global: "latest"

kubectl_plugins:
  - ctx
  - ns
  - cert-manager
  - istiolog
  - mtail
  - outdated
  - preflight
  - support-bundle

kubectl_plugins_unofficial:
  - name: kubectl-version_manager
    url: https://raw.githubusercontent.com/ardikabs/kubectl-version_manager/master/kubectl-version_manager
  - name: kubectl-ssh_jump
    url: https://raw.githubusercontent.com/ardikabs/kubectl-ssh_jump/master/kubectl-ssh_jump
  - name: kubectl-node_shell
    url: https://github.com/kvaps/kubectl-node-shell/raw/master/kubectl-node_shell
