post_install: |
  You need to change your current shell to use zsh.
  With running the following commands:
        chsh -s $(which zsh)

  You also need to run keybase with running the following commands:
        run_keybase

  Then after that you need to import your current pgp key from keybase,
  with running the following commands:
        keybase pgp export -s | gpg --import

# ------ Binary version ------
go_version: "1.16.5"
kubectl_version: "v1.19.4"
sops_version: "v3.6.1"

# ------ Directory ------
fonts_dir: "{% if ansible_system == 'Linux' %}{{ ansible_env.HOME }}/.local/share/fonts{% elif ansible_system == 'Darwin' %}{{ ansible_env.HOME }}/Library/Fonts{% endif %}"
localbin_dir: "{{ ansible_env.HOME }}/.local/bin"
gitconfig_dir: "{{ ansible_env.HOME }}/.local/git"
gnupg_dir : "{{ ansible_env.HOME }}/.gnupg"
ssh_dir : "{{ ansible_env.HOME }}/.ssh"

# ------ Fonts ------
powerline_fonts: no
nerd_fonts: yes
