- name: Install required packages
  apt:
    pkg: "{{ apt_packages }}"
    state: latest
    update_cache: yes
  become: yes
  tags:
    - apt

- name: Purge old docker packages
  apt:
    name:
    - docker
    - docker.io
    - docker-engine
    - runc
    - containerd
    - lxc-docker
    state: absent
    purge: yes
  become: yes
  tags:
    - docker

- name: Add Docker PGP Key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  become: yes
  tags:
    - docker

- name: Add Docker APT Repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
  become: yes
  tags:
    - docker

- name: Installing Docker latest
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  become: yes
  tags:
    - docker

- name: Adding user {{ ansible_env.USER }} to docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: yes
  tags:
    - docker

- name: Download bat.deb
  get_url:
    url: https://github.com/sharkdp/bat/releases/download/v0.16.0/bat_0.16.0_amd64.deb
    dest: /tmp/bat.deb
  tags:
    - apt
    - bat

- name: Install bat.deb
  apt:
    deb: /tmp/bat.deb
  become: yes
  tags:
    - apt
    - bat

- name: Download keybase.deb
  get_url:
    url: https://prerelease.keybase.io/keybase_amd64.deb
    dest: /tmp/keybase_amd64.deb
  tags:
    - apt
    - keybase

- name: Install keybase.deb
  apt:
    deb: /tmp/keybase_amd64.deb
  become: yes
  tags:
    - apt
    - keybase
