
- name: Ensuring Homebrew Is Installed (1)
  stat:
    path: /usr/local/bin/brew
  register: homebrew_check
  tags:
  - brew

- name: Ensuring Homebrew Is Installed (2)
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check
  when:
    - not homebrew_check.stat.exists
  tags:
  - brew

- name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
  fail:
    msg: Homebrew is missing...Install from http://brew.sh/
  when:
    - not homebrew_check.stat.exists
    - not install_homebrew_if_missing
  tags:
  - brew

- name: Installing Homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when:
    - not homebrew_check.stat.exists
    - install_homebrew_if_missing
  tags:
  - brew

- name: Updating Homebrew
  homebrew:
    update_homebrew: true
  when: homebrew_check.stat.exists
  tags:
  - brew

- name: Upgrading Homebrew Packages
  homebrew:
    upgrade_all: "{{ upgrade_homebrew_packages }}"
  register: result
  until: result is successful
  when: homebrew_check.stat.exists
  tags:
  - brew

- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name: "{{ brew_cask_packages }}"
    state: present
  register: result
  until: result is successful
  when: homebrew_check.stat.exists
  tags:
  - brew
  - brew-cask

- name: Installing Homebrew Packages
  homebrew:
    name: "{{ brew_packages }}"
    state: present
  register: result
  until: result is successful
  when: homebrew_check.stat.exists
  tags:
  - brew
