- name: Install required packages
  ansible.builtin.apt:
    pkg: "{{ apt_packages }}"
    state: present
    update_cache: true
  become: true
  tags:
    - apt

- name: Check python exist on the PATH
  ansible.builtin.shell: "which python" # noqa command-instead-of-shell
  register: python_exist
  failed_when: false
  changed_when: false
  tags:
    - python

- name: Link python3 to python
  ansible.builtin.file:
    src: "{{ lookup('pipe', 'which python3') }}"
    dest: /usr/bin/python
    state: link
  become: true
  when: python_exist.rc != 0
  tags:
    - python

- name: Purge old docker packages
  ansible.builtin.apt:
    name:
      - docker
      - docker.io
      - docker-engine
      - runc
      - containerd
      - lxc-docker
    state: absent
    purge: true
  become: true
  tags:
    - docker

- name: Add Docker PGP Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  become: true
  tags:
    - docker

- name: Add Docker APT Repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
  become: true
  tags:
    - docker

- name: Installing Docker latest
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
  become: true
  tags:
    - docker

- name: "Adding user {{ ansible_env.USER }} to docker group"
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: true
  become: true
  tags:
    - docker

- name: Download bat.deb
  ansible.builtin.get_url:
    url: https://github.com/sharkdp/bat/releases/download/v0.16.0/bat_0.16.0_amd64.deb
    dest: /tmp/bat.deb
  tags:
    - apt
    - bat

- name: Install bat.deb
  ansible.builtin.apt:
    deb: /tmp/bat.deb
  become: true
  tags:
    - apt
    - bat

- name: Download keybase.deb
  ansible.builtin.get_url:
    url: https://prerelease.keybase.io/keybase_amd64.deb
    dest: /tmp/keybase_amd64.deb
  tags:
    - apt
    - keybase

- name: Install keybase.deb
  ansible.builtin.apt:
    deb: /tmp/keybase_amd64.deb
  become: true
  tags:
    - apt
    - keybase
