- name: Download powerline-fonts repository from github
  git:
    repo: 'https://github.com/powerline/fonts.git'
    version: master
    dest: /tmp/powerline-fonts
    depth: "1"
  when: powerline_fonts
  tags:
    - powerline-fonts

- name: Copying powerline-fonts
  command: cp -r /tmp/powerline-fonts/{{ item }} {{ fonts_dir }}
  loop:
  - "DroidSansMono"
  - "Meslo Dotted"
  - "Meslo Slashed"
  - "Roboto Mono"
  when: powerline_fonts
  tags:
  - powerline-fonts

- name: Download nerd-fonts
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/{{ item }}.zip
    dest: "{{ fonts_dir }}"
    remote_src: yes
  when: nerd_fonts
  loop:
    - "DroidSansMono"
    - "Meslo"
    - "Go-Mono"
    - "Ubuntu"
    - "UbuntuMono"
  tags:
  - nerd-fonts


- name: Configure font cache
  command: fc-cache -vf {{ fonts_dir }}
  failed_when: yes
  when: ansible_system == "Linux"
