
- name: Install kubectl krew
  shell: |-
    set -x; cd "$(mktemp -d)" &&
    curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz" &&
    tar zxvf krew.tar.gz &&
    KREW=./krew-"$(uname | tr '[:upper:]' '[:lower:]')_$(uname -m | sed -e 's/x86_64/amd64/' -e 's/arm.*$/arm/')" && "$KREW" install krew
  tags:
    - kubectl-krew
    - kubectl-plugins

- name: Install personal kubectl plugin
  get_url:
    url: "{{ item.url }}"
    dest: "{{ ansible_env.HOME }}/.krew/bin/{{ item.name }}"
    mode: "777"
  become: yes
  loop: "{{ kubectl_plugins_unofficial }}"
  tags:
    - kubectl-plugins

- name: Install kubectl plugins
  command: "{{ ansible_env.HOME }}/.krew/bin/kubectl-krew install {{ item }}"
  loop: "{{ kubectl_plugins }}"
  tags:
    - kubectl-plugins
