
- name: Install kubectl krew
  shell: |-
    set -x; cd "$(mktemp -d)" &&
    curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz" &&
    tar zxvf krew.tar.gz &&
    KREW=./krew-"$(uname | tr '[:upper:]' '[:lower:]')_$(uname -m | sed -e 's/x86_64/amd64/' -e 's/arm.*$/arm/')" && "$KREW" install krew
  tags:
    - kubectl-krew

- name: Install personal kubectl plugin
  get_url:
    url: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/.krew/bin/{{ item.name }}"
    mode: "777"
  become: yes
  loop:
    - repo: https://raw.githubusercontent.com/ardikabs/kubectl-version_manager/master/kubectl-version_manager
      name: kubectl-version_manager
    - repo: https://raw.githubusercontent.com/ardikabs/kubectl-ssh_jump/master/kubectl-ssh_jump
      name: kubectl-ssh_jump
  tags:
    - kubectl-plugins

- name: Install kubectl plugins
  command: "{{ ansible_env.HOME }}/.krew/bin/kubectl-krew install {{ item }}"
  loop:
    - ctx
    - ns
    - ingress-nginx
    - cert-manager
  tags:
    - kubectl-plugins
