- name: Install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv"
    version: master
    update: yes
    depth: "1"
  tags:
    - python

- name: Install pyenv-virtualenv
  git:
    repo: https://github.com/yyuu/pyenv-virtualenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv/plugins/pyenv-virtualenv"
    version: master
    update: yes
    depth: "1"
  tags:
    - python

- name: Install poetry
  shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | if [ -x /usr/bin/python3 ]; then python3 -; else python -; fi
  become: yes
  ignore_errors: yes
  tags:
    - python
