- name: Install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv"
    version: master
    update: yes
    depth: "1"
  tags:
    - python

- name: Install pyenv-virtualenv
  git:
    repo: https://github.com/yyuu/pyenv-virtualenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv/plugins/pyenv-virtualenv"
    version: master
    update: yes
    depth: "1"
  tags:
    - python

- name: Install poetry
  shell: curl -sSL https://install.python-poetry.org | python3 - # noqa command-instead-of-module risky-shell-pipe
  become: yes
  changed_when: True
  tags:
    - python
