- name: Download fuzzy finder (fzf)
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ ansible_env.HOME }}/.fzf"
    version: master
    depth: "1"
  tags:
    - fzf

- name: Install direnv
  shell: "curl -sfL https://direnv.net/install.sh | bash"
  args:
    warn: false
  become: yes
  tags:
    - direnv

- name: Install fuzzy finder (fzf)
  shell: "{{ ansible_env.HOME }}/.fzf/install --all --no-fish"
  args:
    executable: /bin/zsh
  tags:
    - fzf

- name: Configure tmux configuration
  command: cp -fr /tmp/dotfiles/tmux/.tmux.conf {{ ansible_env.HOME }}
  ignore_errors: yes
  tags:
    - tmux
    - dotfiles

- name: Download tmux plugin manager
  git:
    repo: 'https://github.com/tmux-plugins/tpm.git'
    version: master
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    depth: "1"
  tags:
    - tmux
    - dotfiles

- name: Configure vim configuration
  command: cp -fr /tmp/dotfiles/vim/.vimrc {{ ansible_env.HOME }}
  ignore_errors: yes
  tags:
    - vim
    - dotfiles

- name: Configure gpg-agent configuration
  command: cp -fr /tmp/dotfiles/gpg/gpg-agent.conf {{ gnupg_dir }}
  tags:
    - gpg
    - dotfiles

- name: Configure gpg sshcontrol configuration
  command: cp -fr /tmp/dotfiles/gpg/sshcontrol {{ gnupg_dir }}
  tags:
    - gpg
    - dotfiles

- name: Configure user ssh configuration
  command: cp -fr /tmp/dotfiles/ssh/config {{ ssh_dir }}
  tags:
    - ssh
    - dotfiles

- name: Configure system ssh configuration
  command: cp -fr /tmp/dotfiles/ssh/ssh_config /etc/ssh/ssh_config
  become: yes
  tags:
    - ssh
    - dotfiles

- name: Configure global gitconfig
  command: cp -fr /tmp/dotfiles/git/.gitconfig {{ ansible_env.HOME}}
  tags:
    - git
    - gitconfig
    - dotfiles

- name: Configure global gitignore
  command: cp -fr /tmp/dotfiles/git/.gitignore {{ ansible_env.HOME}}
  tags:
    - git
    - gitignore
    - dotfiles

- name: Configure additional gitconfigs
  command: cp -fr /tmp/dotfiles/git/.gitconfigs {{ gitconfig_dir }}
  tags:
    - git
    - gitconfigs
    - dotfiles

- name: Configure git templates
  command: cp -fr /tmp/dotfiles/git/.gittemplates {{ gitconfig_dir }}
  tags:
    - git
    - gittemplates
    - dotfiles

- name: Configure git users
  command: cp -fr /tmp/dotfiles/git/.gitusers {{ gitconfig_dir }}
  tags:
    - git
    - gitusers
    - dotfiles

- name: Configure git-custom-command
  command: cp -fr /tmp/dotfiles/git/cmd/ {{ gitconfig_dir }}
  tags:
    - git
    - git-custom-command
    - dotfiles

- name: Install mozilla sops {{ sops_version }}
  get_url:
    url: "https://github.com/mozilla/sops/releases/download/{{ sops_version }}/sops-{{ sops_version }}.{{ ansible_system | lower }}"
    dest: /usr/local/bin/sops
    mode: "777"
  become: yes
  when:
    - ansible_architecture != "arm64"
  tags:
    - binary
    - sops

- name: Install docker-credential-ecr-login
  get_url:
    url: "https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.4.0/{{ ansible_system | lower }}-{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}/docker-credential-ecr-login"
    dest: /usr/local/bin/docker-credential-ecr-login
    mode: "777"
  become: yes
  tags:
    - binary
    - docker
