- name: Configure zsh
  shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
  ignore_errors: yes
  args:
    warn: false
  tags:
    - zsh-install

- name: Configure zsh plugins
  git:
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item.plugin_name }}"
    repo: "{{ item.plugin_repo }}"
    version: master
    depth: "1"
  loop:
  - plugin_name: zsh-syntax-highlighting
    plugin_repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
  - plugin_name: zsh-autosuggestions
    plugin_repo: https://github.com/zsh-users/zsh-autosuggestions
  - plugin_name: zsh-completions
    plugin_repo: https://github.com/zsh-users/zsh-completions
  tags:
    - zsh-plugins

- name: Configure zsh themes
  git:
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/{{ item.plugin_name }}"
    repo: "{{ item.plugin_repo }}"
    version: master
    depth: "1"
  loop:
  - plugin_name: powerlevel10k
    plugin_repo: https://github.com/romkatv/powerlevel10k.git
  tags:
    - zsh-themes

- name: Copy zshrc.d to local directory
  command: "cp -fr /tmp/dotfiles/zsh/zshrc.d {{ ansible_env.HOME }}/.local/"
  tags:
    - zsh-rc
    - dotfiles

- name: Override local .zshrc
  command: "cp -fr /tmp/dotfiles/zsh/.zshrc {{ ansible_env.HOME }}"
  tags:
    - zsh-rc
    - dotfiles

- name: Modify shell user {{ ansible_env.USER }} to /bin/zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: yes
  tags:
    - zsh
