- name: Configure zsh
  ansible.builtin.shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh # noqa risky-shell-pipe
  failed_when: false
  changed_when: true
  args:
    warn: false
  tags:
    - zsh-install

- name: Configure zsh plugins
  ansible.builtin.git:
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item.plugin_name }}"
    repo: "{{ item.plugin_repo }}"
    version: master
    depth: "1"
  loop:
    - plugin_name: zsh-syntax-highlighting
      plugin_repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    - plugin_name: zsh-autosuggestions
      plugin_repo: https://github.com/zsh-users/zsh-autosuggestions
    - plugin_name: zsh-completions
      plugin_repo: https://github.com/zsh-users/zsh-completions
  tags:
    - zsh-plugins

- name: Configure zsh themes
  ansible.builtin.git:
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/{{ item.plugin_name }}"
    repo: "{{ item.plugin_repo }}"
    version: master
    depth: "1"
  loop:
    - plugin_name: powerlevel10k
      plugin_repo: https://github.com/romkatv/powerlevel10k.git
  tags:
    - zsh-themes

- name: Copy zshrc.d to local directory
  ansible.builtin.command: "cp -fr /tmp/dotfiles/zsh/zshrc.d {{ ansible_env.HOME }}/.local/"
  failed_when: false
  changed_when: true
  tags:
    - zsh-rc
    - dotfiles

- name: Override local .zshrc
  ansible.builtin.command: "cp -fr /tmp/dotfiles/zsh/.zshrc {{ ansible_env.HOME }}"
  failed_when: false
  changed_when: true
  tags:
    - zsh-rc
    - dotfiles

- name: Modify shell user {{ ansible_env.USER }} to /bin/zsh
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: true
  tags:
    - zsh
