name: Main workflows

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ansible-version: [stable-2.9]

    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install python3-apt package for ubuntu
        run: sudo apt update -y && sudo apt install python3-apt

      - name: Install ansible
        run: pip install -r requirements.txt --disable-pip-version-check

      - name: Linting the playbook
        run: ansible-lint -v playbook.yaml

      - name: Syntax check the playbook
        run: ansible-playbook -v playbook.yaml --syntax-check

      - name: Dry run the playbook
        run: ansible-playbook -v playbook.yaml
        if: ${{ github.ref == 'refs/heads/master' }}
